#!/bin/sh

set -e

#echo "updating neovim"
cd ~/git/neovim
#git pull
make distclean
make -j $(nproc) CMAKE_BUILD_TYPE=RelWithDebInfo
# sudo make install
make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_INSTALL_PREFIX=~/.local/opt/neovim install
