#!/bin/bash

if [ $1 == "arch" ]; then
    echo "==========================="
    echo "Installation for arch linux"
    echo "==========================="

    echo "Installing yay"
    sudo pacman -S yay

    echo "Installing all the required packages"
    graphics=(\
        ly-git \
        i3 \
        rofi \
        polybar \
        compton \
        nitrogen \
        feh \
        kitty)
    graphics_dependencies=(\
        jsoncpp \
        libnl)
    audio=(\
        libmpdclient \
        alsa-utils \
        alsa-plugins \
        alsa-lib \
        alsa-firmware \
        pulseaudio \
        pulseaudio-alsa \
        pavucontrol \
        clementine)
    terminal=(\
        htop \
        neovim \
        ranger \
        w3m \
        zsh)
    tools=(\
        curl \
        playerctl \
        xclip \
        python-pip)
    drivers=(\
        mesa \
        lib32-mesa \
        libva-mesa-driver \
        lib32-libva-mesa-driver \
        mesa-vdpau \
        lib32-mesa-vdpau \
        xorg \
        xorg-drivers)
    internet=(\
        opera \
        firefox)
    fonts=(\
        otf-fira-code \
        nerd-fonts-fira-mono \
        nerd-fonts-fira-code)

    #yay -S ${graphics[@]} ${graphics_dependencies[@]} ${audio[@]} ${terminal[@]} ${tools[@]} ${drivers[@]} ${internet[@]} ${fonts[@]}

    echo "Changing the shell"
    sudo chsh /bin/zsh $USER

    echo "Installing the python neovim module"
    sudo pip install neovim

    echo "Installing oh-my-zsh"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

    echo "Installing vim-plug"
    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    echo "Installing my configurations"
    git clone https://github.com/luxed/nvim-config ~/.config/nvim
    #git clone https://github.com/luxed/configs ~/git/configs
    cp -r ./home/.config ~/
    cp -r ./home/.zshrc ~/
    cp -r ./home/.oh-my-zsh ~/

    echo "Activating Ly as the default Display Manager"
    sudo systemctl enable ly.service

    echo "=================================="
    echo "Don't forget to update and register plugins for neovim (PlugUpdate and UpdateRemotePlugins)"
    echo "=================================="
fi
