#!/bin/bash

if [ $1 == "arch" ]; then
    echo "==========================="
    echo "Installation for arch linux"
    echo "==========================="

    echo "Installing yay"
    sudo pacman -S yay

    echo "Installing all the required packages"
    graphics=(\
        ly-git \
        i3 \
        rofi \
        polybar \
        compton \
        nitrogen \
        feh \
        kitty)
    graphics_dependencies=(\
        jsoncpp \
        libnl)
    themes=(\
        lxappearance \
        arc-kde \
        arc-gtk-theme \
        arc-icon-theme \
        kvantum-qt5 kvantum-theme-arc)
    audio=(\
        libmpdclient \
        alsa-utils \
        alsa-plugins \
        alsa-lib \
        alsa-firmware \
        pulseaudio \
        pulseaudio-alsa \
        pavucontrol \
        cmus \
        clementine-qt5-git)
    terminal=(\
        htop \
        neovim \
        ranger \
        highlight \
        w3m \
        zsh)
    tools=(\
        curl \
        playerctl \
        xclip \
        transmission-gtk \
        python-pip)
    drivers=(\
        mesa \
        lib32-mesa \
        libva-mesa-driver \
        lib32-libva-mesa-driver \
        mesa-vdpau \
        lib32-mesa-vdpau \
        xorg \
        xorg-drivers)
    internet=(\
        opera \
        firefox)
    fonts=(\
        otf-fira-code \
        nerd-fonts-fira-mono \
        nerd-fonts-fira-code)

    yay -S ${graphics[@]} ${graphics_dependencies[@]} ${themes[@]} ${audio[@]} ${terminal[@]} ${tools[@]} ${drivers[@]} ${internet[@]} ${fonts[@]}

    echo "Changing the shell"
    sudo chsh /bin/zsh $USER

    echo "Installing the python neovim module"
    sudo pip install neovim

    echo "Installing oh-my-zsh"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

    echo "Installing vim-plug"
    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    echo "Installing my configurations"
    git clone https://github.com/luxed/nvim-config ~/.config/nvim
    #git clone https://github.com/luxed/configs ~/git/configs
    cp -r ./home/.config ~/
    cp -r ./home/.zshrc ~/
    cp -r ./home/.oh-my-zsh ~/

    git clone https://github.com/x70b1/polybar-scripts ~/.config/polybar/polybar-scripts

    echo "Activating Ly as the default Display Manager"
    sudo systemctl enable ly.service

    echo "=================================="
    echo "Don't forget to update and register plugins for neovim (PlugUpdate and UpdateRemotePlugins)"
    echo "=================================="
elif [ $1 == "fedora" ]; then
    echo "Installing rpmfusion repositories"
    sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

    echo "Installing all the required packages"
    sudo dnf install i3 rofi polybar playerctl dunst kitty htop ranger zsh lsd bat thefuck flatpak python3 python3-pip npm cmus

    sudo dnf copr enable agriffis/neovim-nightly
    sudo dnf install neovim

    echo "Installing flatpak packages"
    flatpak remote-add --if-not-exists flathub https://flathub.flatpakrepo
    flatpak install slack discord

    echo "Changing the shell to zsh"
    sudo chsh /bin/zsh $USER

    echo "Installing neovim modules"
    sudo pip install neovim
    sudo npm install neovim

    echo "Installing oh-my-zsh"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

    echo "Installing Neovim config"
    git clone https://github.com/luxed/nvim-config.git ~/.config/nvim

    echo "Installing Rustup"
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

    ./create_symlinks.sh
fi
