#!/usr/bin/env bash

# General variables
version_dir="$HOME/scripts/binup-scripts"
output_dir="$HOME/.local/bin"

# Package specific variables
bin_name="rust-analyzer-test"
bin_path="$output_dir/$bin_name"
version_path="$version_dir/$bin_name-version"
release_url="https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/latest"

release_json=$(curl -X GET --url $release_url | jq '.assets[] | select(.name == "rust-analyzer-linux")')
current_version=$(echo "$release_json" | jq '.created_at')
browser_download_url=$(echo "$release_json" | jq '.browser_download_url')

installed_version=""

if [ -f $version_path ]; then
    installed_version=$(cat $version_path)
fi

if [ "$current_version" != "$installed_version" ]; then
    echo "yes"
else
    echo "rust-analyzer is already installed"
fi

#test=$(curl -X GET --url "https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/latest")
#browser_download_url=$(echo "$test" | grep -e 'browser_download_url.*rust-analyzer-linux"' | awk '{print $2}')

# Yeah, I know, that's weird, but it works...
#echo $browser_download_url | xargs -n 1 curl -L -o $bin_name
#chmod +x $bin_name
