#!/bin/bash

set -e

#echo $1

# command to get latest commit: `git log -n1 --format=format:"%H"`

# TODO: allow for a list of packages
# TODO: add a way to verify for dependencies (needs to work for different distributions)

if [ "$1" == "" ]; then
    echo "yeah, no"
    exit 1
fi

pkg_name=$1

# TODO: move this to make it more logical
pkg_build_file="$HOME/scripts/update-$pkg_name"
pkg_git_dir="$HOME/git/$pkg_name"

# TODO: this could be a multi-threaded operation (in the same way that `packer-nvim` does it)
cd $pkg_git_dir
git pull
git submodule update --init --recursive

current_git_hash=$(git log -n1 --format=format:"%H")
old_git_hash=""
if [ -f "$pkg_git_dir/hash_installed" ]; then
    old_git_hash=$(cat "$pkg_git_dir/hash_installed")
fi

if [ "$old_git_hash" != "$current_git_hash" ]; then
    echo "=== Package \"$pkg_name\" is outdated, it will be rebuilt and installed ==="

    $pkg_build_file

    git log -n1 --format=format:"%H" > hash_installed
else
    echo "/!\\ Package \"$pkg_name\" is already at the latest version /!\\"
fi
