#!/bin/bash

# TODO: add a way to verify for dependencies (needs to work for different distributions)

for var in "$@"
do
    if [ "$var" == "" ]; then
        echo "please enter a package name"
        continue
    fi

    pkg_name=$var

    # TODO: move this to make it more logical
    pkg_build_file="$HOME/scripts/pkgup-scripts/$pkg_name"
    pkg_git_dir="$HOME/git/$pkg_name"

    # TODO: this could be a multi-threaded operation (in the same way that `packer-nvim` does it)
    if ! cd $pkg_git_dir; then
        continue
    fi
    git pull
    git submodule update --init --recursive

    current_git_hash=$(git log -n1 --format=format:"%H")
    old_git_hash=""
    if [ -f "$pkg_git_dir/hash_installed" ]; then
        old_git_hash=$(cat "$pkg_git_dir/hash_installed")
    fi

    if [ "$old_git_hash" != "$current_git_hash" ]; then
        echo "=== Package \"$pkg_name\" is outdated, it will be rebuilt and installed ==="

        if ! $pkg_build_file; then
            continue
        fi

        git log -n1 --format=format:"%H" > hash_installed
    else
        echo "/!\\ Package \"$pkg_name\" is already at the latest version /!\\"
    fi
done
