#!/bin/bash

ps aux | awk '!/awk/ && /dwall/ {print $2}' | xargs kill

# dwall possible wallpapers
wallpapers=(bitday exodus firewatch firewatch2 forest home mall room street street2 tokyostreet)
random_number=$(( $RANDOM % ${#wallpapers[@]} ))
random_wallpaper=${wallpapers[$random_number]}

dwall -s $random_wallpaper
